/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjQuitanda;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Igor
 */
public class ConsultaProduto extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaProduto
     */
    public ConsultaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListProd = new javax.swing.JList<>();
        btPesquisa = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Digite o nome do Produto:");

        jScrollPane1.setViewportView(txtListProd);

        btPesquisa.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        btPesquisa.setText("Pesquisar");
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjQuitanda/imagens/shopping-basket (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(txtProduto))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btPesquisa)
                .addGap(31, 31, 31)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisa)
                    .addComponent(btExcluir)
                    .addComponent(btEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        
            String[] itens = new String[4];
            itens = txtListProd.getSelectedValue().split("-");
            if(itens.equals("")){
                JOptionPane.showMessageDialog(null, "Selecione um ");
            }
            int id = Integer.parseInt(itens[0]);
            Statement st;
            Conexao conex = new Conexao();
            System.out.print(id);
            String sqlSelect = "select * from tb_produtos where id_produto = '"+id+"'";
            conex.conectar();
            try{
            st = Conexao.con.createStatement();
            ResultSet set = st.executeQuery(sqlSelect);
            if(set.next()){
                System.out.print("iaushdiaushd");
            }
            System.out.print(set.getString("nome_produto"));
            EditarProduto ed = new EditarProduto(set.getInt("id_produto"),set.getString("nome_produto"), set.getString("valor_produto"), set.getString("descricao"), set.getString("dt_validade"),set.getString("alias"));
            ed.setVisible(true);
            ed.setLocationRelativeTo(null);
            }catch(SQLException ex){
                System.out.print(ex.getCause());
            }
            
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        // TODO add your handling code here:
        String produto = txtProduto.getText();
        Statement meustate;
        ResultSet rs;
        DefaultListModel list = new DefaultListModel();
        Conexao conex = new Conexao();  
         
        String sql = "select * from tb_produtos where alias = '"+produto+"'";
         
        conex.conectar();
        try{
        meustate = Conexao.con.createStatement();
        rs =  meustate.executeQuery(sql);
        if(!rs.next()){
            JOptionPane.showMessageDialog(null, "Produto não encontrado!");
            return;
        }else{
            list.addElement(rs.getInt("id_produto") + "-" +rs.getString("nome_produto")+ "-" +rs.getString("valor_produto")+ "-" +rs.getString("dt_validade"));
        }
        txtListProd.setModel(list);
        }catch(SQLException ex){
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        Statement meustate;
        String[] item = new String[4];
        Conexao conex = new Conexao();  
         DefaultListModel list = new DefaultListModel();
        
        System.out.print(txtListProd.getSelectedValue());
         item = txtListProd.getSelectedValue().split("-");
        System.out.print(item[0]);
        
        String sql = "delete from tb_produtos where "
        + "id_produto = '"+ item[0] +"'"; 
        conex.conectar();
         
       try{
             meustate = Conexao.con.createStatement();
             meustate.executeUpdate(sql);
             txtProduto.setText("");             
             JOptionPane.showMessageDialog(null,"Produto Excluído com sucesso");
             txtListProd.setModel(list);
         }
         catch(SQLException erro){
             System.out.print(erro.getMessage());
         }
        conex.desconectar();
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optiobtEditar        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> txtListProd;
    private javax.swing.JTextField txtProduto;
    // End of variables declaration//GEN-END:variables
}
